import Head from "next/head";
import { Box, Button, Container, Flex } from "@chakra-ui/react";
import Arweave from "arweave";
import React, { useState } from "react";

export default function Home() {
  const arweave = Arweave.init({});
  const [isConnected, setIsConnected] = useState(false);

  const perms = [
    "ACCESS_ADDRESS",
    "ACCESS_PUBLIC_KEY",
    "ACCESS_ALL_ADDRESSES",
    "SIGN_TRANSACTION",
  ];

  const appDetails = {
    name: "my special app",
    logo: "icon.png",
  };

  // wallet to wallet simple
  async function sendTx() {
    const tx = await arweave.createTransaction({
      target: "i_0lXhTIsKKABEKYNlNTiKtY3QTbo9Dm56uzEvvi85g",
      quantity: arweave.ar.arToWinston("0.05"),
    });

    await arweave.transactions.sign(tx);
    const response = await arweave.transactions.post(tx);
    console.log(response.status);
  }

  async function connectWallet() {
    await window.arweaveWallet.connect(perms, appDetails);
    setIsConnected(true);
  }

  async function disconnectWallet() {
    await window.arweaveWallet.disconnect();
    setIsConnected(false);
  }

  // uncomment this to try and connect wallet on page load
  //if (typeof window !== "undefined") {
  //connectWallet();
  //}

  if (typeof window !== "undefined") {
    window.addEventListener("walletSwitch", (e) => {
      const newAddress = e.detail.address;
      setAccounts(newAddress);
    });
  }

  return (
    <Box>
      <Head>
        <title>ArConnect dApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="logo.png" />
      </Head>
      <Container maxW="container.xl" pt={2}>
        <Flex justify="flex-end" mt={4}>
          {isConnected ? (
            <Button onClick={disconnectWallet}>Disconnect!</Button>
          ) : (
            <Button onClick={connectWallet}>Connect!</Button>
          )}
        </Flex>
        <Container centerContent>
        <Button onClick={sendTx}>Send a tip!</Button>
        </Container>
      </Container>
    </Box>
  );
}
